site_name: MkDocs Plugins
site_url: "https://oprypin.github.io/mkdocs-gen-files"
repo_url: "https://github.com/oprypin/mkdocs-gen-files"
edit_uri: blob/master/docs/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: teal
    accent: purple

extra_css:
  - assets/style.css
extra_javascript:
  - assets/script.js

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_pages.py
  - awesome-pages
  - section-index
  - mkdocstrings:
      watch: [mkdocs_gen_files]
      handlers:
        python:
          rendering:
            show_signature_annotations: true
            show_source: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - def_list
  - toc:
      permalink: "#"

nav:
  - mkdocstrings-crystal: /mkdocstrings-crystal/
  - section-index: /mkdocs-section-index/
  - literate-nav: /mkdocs-literate-nav/
  - gen-files:
    - index.md
    - API: api.md
    - ...
  - same-dir: /mkdocs-same-dir/
